version: "3.6"

volumes:
  minio-data:
    driver: local

services:
  minio:
    image: minio/minio
    volumes:
      - minio-data:/data
    command: server /data
    environment:
      MINIO_DOMAIN: localhost
      MINIO_ACCESS_KEY: AKIAIOSFODNN7EXAMPLE
      MINIO_SECRET_KEY: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
    ports:
      - 9000:9000

